import 'bootstrap/dist/css/bootstrap.css'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from '../../node_modules/next/link'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'
import { AppBar, Box, Button, ButtonBase, ButtonGroup, Container, CssBaseline, Menu, MenuItem, Stack, StyledEngineProvider, ThemeProvider, Toolbar } from '@mui/material'
import Image from 'next/image'
import styled from '@emotion/styled/types/base'
import KeyboardArrowDown from '@mui/icons-material/KeyboardArrowDown'
import React from 'react'
import { Console } from 'console'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Bank Poc Web',
  description: 'Generated by create next app',
}

// const ImageButton = styled(ButtonBase)(({})=> ({
//   position: 'relative',
//   height:'100%',
//   width:'100%'
// })) 

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // const [applyDropdown, setApplyDropdown] = React.useState<null | HTMLElement>(null);
  // const open = Boolean(applyDropdown);
  // const applyButtonClick = (event: React.MouseEvent<HTMLElement>) => {
  //   setApplyDropdown(event.currentTarget);
  //   {console.log(open)}
  // }
  // const handleClose = () => {
  //   setApplyDropdown(null)
  // }
  return (
    <html lang="en">
      <body className={inter.className}>
          <CssBaseline />
          <AppBar position='fixed' className='app-bar'>
            <Container maxWidth='xl' className='app-barq'>
              <Toolbar disableGutters>
                <Link href ="/" color='inherit'>care credit</Link>
                <Box sx={{ flexGrow: 1 }} />
                <Stack direction='row' spacing={1}>
                  <Link href="/purchase">Purchase</Link>
                  <Link href="/refund">Refund</Link>
                  <Link href="/apply">Reports</Link>
                  <Link href="/lookup">Lookup</Link>
                  <Link href="/apply">Apply</Link>
                </Stack>
              </Toolbar>
            </Container>
          </AppBar>
          <Box
            component="main"
            sx={{
              flexGrow: 1,
              p: 3,
              mt: ['48px', '56px', '64px']
            }}
          >   
            </Box>
        {children}
      </body>
    </html>
  )
}
